# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Protos.Authentication import ElaAuthenticationCommon_pb2 as Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2
from Protos.Common import ElaCommon_pb2 as Protos_dot_Common_dot_ElaCommon__pb2


class ElaAuthenticationPublicServiceStub(object):
    """The BackendConfig service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/ElaAuthentication.ElaAuthenticationPublicService/Login',
                request_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaAuthenticationRequest.SerializeToString,
                response_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaAuthenticationResponse.FromString,
                )
        self.Logout = channel.unary_unary(
                '/ElaAuthentication.ElaAuthenticationPublicService/Logout',
                request_serializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaInputBaseRequest.SerializeToString,
                response_deserializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaError.FromString,
                )
        self.CheckAuthorization = channel.unary_unary(
                '/ElaAuthentication.ElaAuthenticationPublicService/CheckAuthorization',
                request_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.SerializeToString,
                response_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserResponse.FromString,
                )
        self.CreateUser = channel.unary_unary(
                '/ElaAuthentication.ElaAuthenticationPublicService/CreateUser',
                request_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.SerializeToString,
                response_deserializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaError.FromString,
                )
        self.GetUsers = channel.unary_unary(
                '/ElaAuthentication.ElaAuthenticationPublicService/GetUsers',
                request_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.SerializeToString,
                response_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaAuthenticationUserList.FromString,
                )
        self.UpdateUser = channel.unary_unary(
                '/ElaAuthentication.ElaAuthenticationPublicService/UpdateUser',
                request_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.SerializeToString,
                response_deserializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaError.FromString,
                )
        self.DeleteUser = channel.unary_unary(
                '/ElaAuthentication.ElaAuthenticationPublicService/DeleteUser',
                request_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.SerializeToString,
                response_deserializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaError.FromString,
                )
        self.LoadLicence = channel.unary_unary(
                '/ElaAuthentication.ElaAuthenticationPublicService/LoadLicence',
                request_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaLicenceRequest.SerializeToString,
                response_deserializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaError.FromString,
                )
        self.RevokeLicence = channel.unary_unary(
                '/ElaAuthentication.ElaAuthenticationPublicService/RevokeLicence',
                request_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaLicenceRequest.SerializeToString,
                response_deserializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaError.FromString,
                )
        self.CheckUserRights = channel.unary_unary(
                '/ElaAuthentication.ElaAuthenticationPublicService/CheckUserRights',
                request_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsRequest.SerializeToString,
                response_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsResponse.FromString,
                )
        self.EnrollInstance = channel.unary_unary(
                '/ElaAuthentication.ElaAuthenticationPublicService/EnrollInstance',
                request_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsRequest.SerializeToString,
                response_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsResponse.FromString,
                )
        self.GetEnrolledInstance = channel.unary_unary(
                '/ElaAuthentication.ElaAuthenticationPublicService/GetEnrolledInstance',
                request_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsRequest.SerializeToString,
                response_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsResponse.FromString,
                )
        self.ReleasedEnrolledInstance = channel.unary_unary(
                '/ElaAuthentication.ElaAuthenticationPublicService/ReleasedEnrolledInstance',
                request_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsRequest.SerializeToString,
                response_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsResponse.FromString,
                )
        self.getNumberLicence = channel.unary_unary(
                '/ElaAuthentication.ElaAuthenticationPublicService/getNumberLicence',
                request_serializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaInputBaseRequest.SerializeToString,
                response_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaNumberLicenceResponse.FromString,
                )


class ElaAuthenticationPublicServiceServicer(object):
    """The BackendConfig service definition.
    """

    def Login(self, request, context):
        """RPC definition

        main login function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAuthorization(self, request, context):
        """check authentication function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """main users function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadLicence(self, request, context):
        """/////////////////////////////////////////////////////////////////////////////////////////
        ADDITIONNAL FUNCTION LICENCE
        main licence management function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeLicence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserRights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrollInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnrolledInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleasedEnrolledInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getNumberLicence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ElaAuthenticationPublicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaAuthenticationRequest.FromString,
                    response_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaAuthenticationResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaInputBaseRequest.FromString,
                    response_serializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaError.SerializeToString,
            ),
            'CheckAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAuthorization,
                    request_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.FromString,
                    response_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.FromString,
                    response_serializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaError.SerializeToString,
            ),
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.FromString,
                    response_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaAuthenticationUserList.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.FromString,
                    response_serializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaError.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.FromString,
                    response_serializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaError.SerializeToString,
            ),
            'LoadLicence': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadLicence,
                    request_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaLicenceRequest.FromString,
                    response_serializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaError.SerializeToString,
            ),
            'RevokeLicence': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeLicence,
                    request_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaLicenceRequest.FromString,
                    response_serializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaError.SerializeToString,
            ),
            'CheckUserRights': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserRights,
                    request_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsRequest.FromString,
                    response_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsResponse.SerializeToString,
            ),
            'EnrollInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrollInstance,
                    request_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsRequest.FromString,
                    response_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsResponse.SerializeToString,
            ),
            'GetEnrolledInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnrolledInstance,
                    request_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsRequest.FromString,
                    response_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsResponse.SerializeToString,
            ),
            'ReleasedEnrolledInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleasedEnrolledInstance,
                    request_deserializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsRequest.FromString,
                    response_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsResponse.SerializeToString,
            ),
            'getNumberLicence': grpc.unary_unary_rpc_method_handler(
                    servicer.getNumberLicence,
                    request_deserializer=Protos_dot_Common_dot_ElaCommon__pb2.ElaInputBaseRequest.FromString,
                    response_serializer=Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaNumberLicenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ElaAuthentication.ElaAuthenticationPublicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ElaAuthenticationPublicService(object):
    """The BackendConfig service definition.
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElaAuthentication.ElaAuthenticationPublicService/Login',
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaAuthenticationRequest.SerializeToString,
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaAuthenticationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElaAuthentication.ElaAuthenticationPublicService/Logout',
            Protos_dot_Common_dot_ElaCommon__pb2.ElaInputBaseRequest.SerializeToString,
            Protos_dot_Common_dot_ElaCommon__pb2.ElaError.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElaAuthentication.ElaAuthenticationPublicService/CheckAuthorization',
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.SerializeToString,
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElaAuthentication.ElaAuthenticationPublicService/CreateUser',
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.SerializeToString,
            Protos_dot_Common_dot_ElaCommon__pb2.ElaError.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElaAuthentication.ElaAuthenticationPublicService/GetUsers',
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.SerializeToString,
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaAuthenticationUserList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElaAuthentication.ElaAuthenticationPublicService/UpdateUser',
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.SerializeToString,
            Protos_dot_Common_dot_ElaCommon__pb2.ElaError.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElaAuthentication.ElaAuthenticationPublicService/DeleteUser',
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaManagerUserRequest.SerializeToString,
            Protos_dot_Common_dot_ElaCommon__pb2.ElaError.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadLicence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElaAuthentication.ElaAuthenticationPublicService/LoadLicence',
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaLicenceRequest.SerializeToString,
            Protos_dot_Common_dot_ElaCommon__pb2.ElaError.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RevokeLicence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElaAuthentication.ElaAuthenticationPublicService/RevokeLicence',
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaLicenceRequest.SerializeToString,
            Protos_dot_Common_dot_ElaCommon__pb2.ElaError.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckUserRights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElaAuthentication.ElaAuthenticationPublicService/CheckUserRights',
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsRequest.SerializeToString,
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnrollInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElaAuthentication.ElaAuthenticationPublicService/EnrollInstance',
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsRequest.SerializeToString,
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEnrolledInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElaAuthentication.ElaAuthenticationPublicService/GetEnrolledInstance',
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsRequest.SerializeToString,
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReleasedEnrolledInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElaAuthentication.ElaAuthenticationPublicService/ReleasedEnrolledInstance',
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsRequest.SerializeToString,
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaUserRightsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getNumberLicence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElaAuthentication.ElaAuthenticationPublicService/getNumberLicence',
            Protos_dot_Common_dot_ElaCommon__pb2.ElaInputBaseRequest.SerializeToString,
            Protos_dot_Authentication_dot_ElaAuthenticationCommon__pb2.ElaNumberLicenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
