# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/Bluetooth/ElaBluetoothCommon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bluetooth.Protos.Common import ElaCommon_pb2 as Protos_dot_Common_dot_ElaCommon__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Protos/Bluetooth/ElaBluetoothCommon.proto',
  package='ElaBluetooth',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)Protos/Bluetooth/ElaBluetoothCommon.proto\x12\x0c\x45laBluetooth\x1a\x1dProtos/Common/ElaCommon.proto\"\xd7\x02\n\x12\x45laBluetoothFilter\x12\x1b\n\x13\x66ilter_match_string\x18\x01 \x01(\t\x12\x19\n\x11\x66ilter_white_list\x18\x02 \x03(\t\x12\x1b\n\x13\x66ilter_maximum_rssi\x18\x03 \x01(\x05\x12#\n\x1b\x66ilter_only_manufacturer_id\x18\x04 \x01(\x08\x12\x1f\n\x17\x66ilter_only_connectable\x18\x05 \x01(\x08\x12@\n\x0b\x66ilter_type\x18\x06 \x01(\x0e\x32+.ElaBluetooth.ElaBluetoothFilter.FilterType\"d\n\nFilterType\x12\r\n\tNo_Option\x10\x00\x12\x10\n\x0cMatch_String\x10\x01\x12\x0e\n\nWhite_List\x10\x02\x12\x10\n\x0cMaximum_Rssi\x10\x03\x12\x13\n\x0fManufacturer_ID\x10\x04\"\xe9\x02\n\x1a\x45laBluetoothScanResultItem\x12\x12\n\ntime_stamp\x18\x01 \x01(\t\x12\x13\n\x0bmac_address\x18\x02 \x01(\t\x12\x12\n\nlocal_name\x18\x03 \x01(\t\x12\x0c\n\x04rssi\x18\x04 \x01(\x05\x12\r\n\x05\x66lags\x18\x05 \x01(\r\x12\x13\n\x0b\x63onnectable\x18\x06 \x01(\x08\x12\x18\n\x10num_service_data\x18\x07 \x01(\r\x12\x1a\n\x12service_data_array\x18\x08 \x03(\t\x12\x14\n\x0cservice_uuid\x18\t \x01(\r\x12\x17\n\x0fmanufacturer_id\x18\n \x01(\r\x12\x19\n\x11manufacturer_data\x18\x0b \x03(\t\x12\x0f\n\x07payload\x18\x0c \x01(\t\x12\x16\n\x0egps_coordinate\x18\r \x01(\t\x12\x17\n\x0fmicroservice_id\x18\x0e \x01(\t\x12\x1a\n\x12\x65la_base_data_json\x18\x0f \x01(\t\"i\n\x1a\x45laBluetoothScanResultList\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x39\n\x07results\x18\x02 \x03(\x0b\x32(.ElaBluetooth.ElaBluetoothScanResultItem\"\x80\x02\n\x17\x45laBluetoothScanResults\x12\"\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x13.ElaCommon.ElaError\x12=\n\x13\x63urrent_filter_info\x18\x02 \x01(\x0b\x32 .ElaBluetooth.ElaBluetoothFilter\x12#\n\x1btotal_scanned_items_counter\x18\x03 \x01(\r\x12\"\n\x1alast_scanned_items_counter\x18\x04 \x01(\r\x12\x39\n\x07scanned\x18\x05 \x01(\x0b\x32(.ElaBluetooth.ElaBluetoothScanResultListb\x06proto3'
  ,
  dependencies=[Protos_dot_Common_dot_ElaCommon__pb2.DESCRIPTOR,])



_ELABLUETOOTHFILTER_FILTERTYPE = _descriptor.EnumDescriptor(
  name='FilterType',
  full_name='ElaBluetooth.ElaBluetoothFilter.FilterType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='No_Option', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Match_String', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='White_List', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Maximum_Rssi', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Manufacturer_ID', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=334,
  serialized_end=434,
)
_sym_db.RegisterEnumDescriptor(_ELABLUETOOTHFILTER_FILTERTYPE)


_ELABLUETOOTHFILTER = _descriptor.Descriptor(
  name='ElaBluetoothFilter',
  full_name='ElaBluetooth.ElaBluetoothFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter_match_string', full_name='ElaBluetooth.ElaBluetoothFilter.filter_match_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_white_list', full_name='ElaBluetooth.ElaBluetoothFilter.filter_white_list', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_maximum_rssi', full_name='ElaBluetooth.ElaBluetoothFilter.filter_maximum_rssi', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_only_manufacturer_id', full_name='ElaBluetooth.ElaBluetoothFilter.filter_only_manufacturer_id', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_only_connectable', full_name='ElaBluetooth.ElaBluetoothFilter.filter_only_connectable', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_type', full_name='ElaBluetooth.ElaBluetoothFilter.filter_type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ELABLUETOOTHFILTER_FILTERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=434,
)


_ELABLUETOOTHSCANRESULTITEM = _descriptor.Descriptor(
  name='ElaBluetoothScanResultItem',
  full_name='ElaBluetooth.ElaBluetoothScanResultItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='ElaBluetooth.ElaBluetoothScanResultItem.time_stamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mac_address', full_name='ElaBluetooth.ElaBluetoothScanResultItem.mac_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='local_name', full_name='ElaBluetooth.ElaBluetoothScanResultItem.local_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rssi', full_name='ElaBluetooth.ElaBluetoothScanResultItem.rssi', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flags', full_name='ElaBluetooth.ElaBluetoothScanResultItem.flags', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connectable', full_name='ElaBluetooth.ElaBluetoothScanResultItem.connectable', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_service_data', full_name='ElaBluetooth.ElaBluetoothScanResultItem.num_service_data', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service_data_array', full_name='ElaBluetooth.ElaBluetoothScanResultItem.service_data_array', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service_uuid', full_name='ElaBluetooth.ElaBluetoothScanResultItem.service_uuid', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='manufacturer_id', full_name='ElaBluetooth.ElaBluetoothScanResultItem.manufacturer_id', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='manufacturer_data', full_name='ElaBluetooth.ElaBluetoothScanResultItem.manufacturer_data', index=10,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='ElaBluetooth.ElaBluetoothScanResultItem.payload', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gps_coordinate', full_name='ElaBluetooth.ElaBluetoothScanResultItem.gps_coordinate', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='microservice_id', full_name='ElaBluetooth.ElaBluetoothScanResultItem.microservice_id', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ela_base_data_json', full_name='ElaBluetooth.ElaBluetoothScanResultItem.ela_base_data_json', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=798,
)


_ELABLUETOOTHSCANRESULTLIST = _descriptor.Descriptor(
  name='ElaBluetoothScanResultList',
  full_name='ElaBluetooth.ElaBluetoothScanResultList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientId', full_name='ElaBluetooth.ElaBluetoothScanResultList.clientId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='results', full_name='ElaBluetooth.ElaBluetoothScanResultList.results', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=800,
  serialized_end=905,
)


_ELABLUETOOTHSCANRESULTS = _descriptor.Descriptor(
  name='ElaBluetoothScanResults',
  full_name='ElaBluetooth.ElaBluetoothScanResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='ElaBluetooth.ElaBluetoothScanResults.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_filter_info', full_name='ElaBluetooth.ElaBluetoothScanResults.current_filter_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_scanned_items_counter', full_name='ElaBluetooth.ElaBluetoothScanResults.total_scanned_items_counter', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_scanned_items_counter', full_name='ElaBluetooth.ElaBluetoothScanResults.last_scanned_items_counter', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scanned', full_name='ElaBluetooth.ElaBluetoothScanResults.scanned', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=908,
  serialized_end=1164,
)

_ELABLUETOOTHFILTER.fields_by_name['filter_type'].enum_type = _ELABLUETOOTHFILTER_FILTERTYPE
_ELABLUETOOTHFILTER_FILTERTYPE.containing_type = _ELABLUETOOTHFILTER
_ELABLUETOOTHSCANRESULTLIST.fields_by_name['results'].message_type = _ELABLUETOOTHSCANRESULTITEM
_ELABLUETOOTHSCANRESULTS.fields_by_name['error'].message_type = Protos_dot_Common_dot_ElaCommon__pb2._ELAERROR
_ELABLUETOOTHSCANRESULTS.fields_by_name['current_filter_info'].message_type = _ELABLUETOOTHFILTER
_ELABLUETOOTHSCANRESULTS.fields_by_name['scanned'].message_type = _ELABLUETOOTHSCANRESULTLIST
DESCRIPTOR.message_types_by_name['ElaBluetoothFilter'] = _ELABLUETOOTHFILTER
DESCRIPTOR.message_types_by_name['ElaBluetoothScanResultItem'] = _ELABLUETOOTHSCANRESULTITEM
DESCRIPTOR.message_types_by_name['ElaBluetoothScanResultList'] = _ELABLUETOOTHSCANRESULTLIST
DESCRIPTOR.message_types_by_name['ElaBluetoothScanResults'] = _ELABLUETOOTHSCANRESULTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ElaBluetoothFilter = _reflection.GeneratedProtocolMessageType('ElaBluetoothFilter', (_message.Message,), {
  'DESCRIPTOR' : _ELABLUETOOTHFILTER,
  '__module__' : 'Protos.Bluetooth.ElaBluetoothCommon_pb2'
  # @@protoc_insertion_point(class_scope:ElaBluetooth.ElaBluetoothFilter)
  })
_sym_db.RegisterMessage(ElaBluetoothFilter)

ElaBluetoothScanResultItem = _reflection.GeneratedProtocolMessageType('ElaBluetoothScanResultItem', (_message.Message,), {
  'DESCRIPTOR' : _ELABLUETOOTHSCANRESULTITEM,
  '__module__' : 'Protos.Bluetooth.ElaBluetoothCommon_pb2'
  # @@protoc_insertion_point(class_scope:ElaBluetooth.ElaBluetoothScanResultItem)
  })
_sym_db.RegisterMessage(ElaBluetoothScanResultItem)

ElaBluetoothScanResultList = _reflection.GeneratedProtocolMessageType('ElaBluetoothScanResultList', (_message.Message,), {
  'DESCRIPTOR' : _ELABLUETOOTHSCANRESULTLIST,
  '__module__' : 'Protos.Bluetooth.ElaBluetoothCommon_pb2'
  # @@protoc_insertion_point(class_scope:ElaBluetooth.ElaBluetoothScanResultList)
  })
_sym_db.RegisterMessage(ElaBluetoothScanResultList)

ElaBluetoothScanResults = _reflection.GeneratedProtocolMessageType('ElaBluetoothScanResults', (_message.Message,), {
  'DESCRIPTOR' : _ELABLUETOOTHSCANRESULTS,
  '__module__' : 'Protos.Bluetooth.ElaBluetoothCommon_pb2'
  # @@protoc_insertion_point(class_scope:ElaBluetooth.ElaBluetoothScanResults)
  })
_sym_db.RegisterMessage(ElaBluetoothScanResults)


# @@protoc_insertion_point(module_scope)
